language: python
python:
  - pypy3

addons:
  apt:
    packages:
      - liblua5.2-dev

env:
  - LUA=lua5.2

before_script:
  # virtualenv<14.0.0 is needed for Python 3.2 support
  - pip install -U tox-travis "virtualenv<14.0.0"
  - if [[ "$LUA" == "lua5.2" ]]; then export SETUP_OPTIONS="--no-luajit" ; fi

script: tox
