language: python
python:
  - 3.5
  - 3.4
  - 3.3
  - 3.2
  - 2.7
  - 2.6

addons:
  apt:
    packages:
      - libluajit-5.1-dev
      - liblua5.2-dev

env:
  - LUA=luajit-5.1
  - LUA=lua5.2

cache: pip


# requirements.txt are automatically installed during 'install' phase.

before_script:
  # virtualenv<14.0.0 is needed for Python 3.2 support
  - pip install -U tox-travis "virtualenv<14.0.0"

  - if [[ "$LUA" == "lua5.2" ]]; then export SETUP_OPTIONS="--no-luajit" ; fi

script: tox
